# Generated by Django 2.2 on 2019-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='floor',
            field=models.IntegerField(help_text='На каком этаже находится помещение'),
        ),
    ]
