# Generated by Django 2.2 on 2019-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190427_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='price',
            field=models.IntegerField(help_text='Цена'),
        ),
        migrations.AlterField(
            model_name='area',
            name='square',
            field=models.IntegerField(help_text='Площадь помещения'),
        ),
        migrations.AlterField(
            model_name='typearea',
            name='name',
            field=models.CharField(blank=True, choices=[('of', 'office'), ('st', 'stock'), ('sc', 'shopping_center')], default='of', max_length=2),
        ),
    ]
