# Generated by Django 2.2 on 2019-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190510_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typearea',
            name='name',
            field=models.CharField(blank=True, choices=[('of', 'office'), ('st', 'stock'), ('sh', 'shopping_center')], default='of', max_length=2),
        ),
    ]
