# Generated by Django 2.2 on 2019-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190510_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typearea',
            name='name',
            field=models.CharField(blank=True, choices=[('office', 'office'), ('stock', 'stock'), ('shopping', 'shopping_center')], default='office', max_length=7),
        ),
    ]
