# Generated by Django 2.2 on 2019-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190510_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Какие коммуникации присутствуют в данном помещении', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='communication',
        ),
        migrations.AlterField(
            model_name='typearea',
            name='name',
            field=models.CharField(blank=True, choices=[('Office', 'office'), ('Stock', 'stock'), ('Shopping', 'shopping_center')], default='Office', max_length=10),
        ),
        migrations.AddField(
            model_name='area',
            name='communication',
            field=models.ManyToManyField(help_text='Вода, отопление,электрическтво', to='catalog.Communication'),
        ),
    ]
