# Generated by Django 2.2 on 2019-05-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190511_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typearea',
            name='name',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('Stock', 'Stock'), ('Shopping', 'Shopping_center')], default='Office', max_length=10),
        ),
    ]
