# Generated by Django 2.2 on 2019-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190511_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['endOfRental']},
        ),
        migrations.AddField(
            model_name='area',
            name='endOfRental',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'Free'), ('b', 'Busy')], default='f', help_text='Area availability', max_length=1),
        ),
    ]
