# Generated by Django 2.2 on 2019-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190511_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Busy', 'Busy')], default='Free', help_text='Area availability', max_length=4),
        ),
    ]
