# Generated by Django 2.2 on 2019-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190511_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['endOfRental'], 'permissions': (('can_mark_singled_out ', 'Set area as free'),)},
        ),
        migrations.AddField(
            model_name='area',
            name='begofRental',
            field=models.TextField(default='', help_text='Где находится'),
            preserve_default=False,
        ),
    ]
