# Generated by Django 2.2 on 2019-05-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190528_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='begofRental',
        ),
    ]
